server:
  port: 8083
spring:
  profiles:
    active: dev
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: order
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://127.0.0.1:8081/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    nonSecurePort: ${server.port}
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}